### PR TITLE
Complete nodejs based buildprocess: jshint, uglifyjs compression

### PR DESCRIPTION
**Pull request by rwaldron**
I hope this contribution isn't seen as being too presumptuous, it is certainly not my intention to assume that I understand the goals for your project. That being said, I think the concept is tremendously cool and I'm very interested in contributing in whatever ways you may need - think of this pull request as a "peace offering" haha

Included here is complete Makefile based build process that uses node.js to run the source through JSHint (jshint.org) and compress it with Uglify.js (https://github.com/mishoo/UglifyJS/)

### CODE REVIEW

**Comment by rwaldron** [comment]
Also, this resolves issue #4

**Comment by rwaldron** [comment]
If you're into this one, then I have another that passes the test suite and jshint 100%, 

I'm holding off on a pull request as it's blocked by this

https://github.com/rwldrn/JSONSelect/tree/hintpass2

**Comment by lloyd** [comment]
wow, neat.  grokking in progress.

**Comment by rwaldron** [comment]
Are you on IRC at all?

**Comment by lloyd** [comment]
rwldrn lth on freenode, lloyd on irc.mozilla.org.

meet in freenode #jsonselect?

**Pull request merged**
